NUM_TYPES_OF_SPARSE_FEATURES = 526
MAX_NUM_ACTIVE_SPARSE_FEATURES = 33

SEAT_INDEX = 2
SEAT_OFFSET = 7

NUM_NUMERIC_FEATURES = 6

NUM_TYPES_OF_PROGRESSION_FEATURES = 2165
# The following number is actually 106. However, it is set to 113 for
# suitable alignment.
MAX_LENGTH_OF_PROGRESSION_FEATURES = 113

NUM_TYPES_OF_ACTIONS = 546
# The following number is actually 30. However, it is set to 32 for
# suitable alignment.
MAX_NUM_ACTION_CANDIDATES = 32

ENCODER_WIDTH = MAX_NUM_ACTIVE_SPARSE_FEATURES + NUM_NUMERIC_FEATURES \
              + MAX_LENGTH_OF_PROGRESSION_FEATURES + MAX_NUM_ACTION_CANDIDATES
