#!/usr/bin/env bash

set -euo pipefail

script_dir="$(dirname "$(readlink -e "${BASH_SOURCE[0]}")")"
prologue_sh_path="$(readlink -e "$script_dir/../prologue.sh")"
. "$prologue_sh_path"
unset prologue_sh_path
unset script_dir

PROGRAM_NAME=install
URL_PREFIX='https://ftpmirror.gnu.org/gcc/'

function print_usage ()
{
  cat <<'EOF'
Usage: install [OPTION]...
Install GCC.

  --version=<VERSION>        The version of GCC to install (default: the
                             latest release version).
  --prefix=<PREFIX>          Pass `--prefix=<PREFIX>' on to GCC `configure'
                             script (default: `/usr/local').
  --source-dir=<DIR>         The source directory (default:
                             `<PREFIX>/src/gcc').
  --clobber-source-dir       Delete the source directory before the source
                             archive is expanded there.
  -h, --help                 Display this help and exit.
EOF
}

if getopt -T; (( $? != 4 )); then
  die_with_runtime_error "$PROGRAM_NAME" "\`getopt' is not an enhanced version."
fi
opts="$(getopt -n "$PROGRAM_NAME" -l version:,prefix:,source-dir:,clobber-source-dir,help -- h "$@")"
eval set -- "$opts"

while (( $# > 0 )); do
  arg="$1"
  shift
  case "$arg" in
  --version)
    if (( $# == 0 )); then
      die_with_logic_error "$PROGRAM_NAME"
    fi
    version="$1"
    shift
    ;;
  --prefix)
    if (( $# == 0 )); then
      die_with_logic_error "$PROGRAM_NAME"
    fi
    prefix="$1"
    shift
    ;;
  --source-dir)
    if (( $# == 0 )); then
      die_with_logic_error "$PROGRAM_NAME"
    fi
    source_dir="$1"
    shift
    ;;
  --clobber-source-dir)
    clobber_source_dir=yes
    ;;
  -h|--help)
    set +x
    print_usage
    exit 0
    ;;
  --)
    if (( $# > 0 )); then
      die_with_user_error "$PROGRAM_NAME" "An invalid argument \`$1'."
    fi
    break
    ;;
  *)
    die_with_user_error "$PROGRAM_NAME" "An invalid argument \`$arg'."
    ;;
  esac
done

configure_options=()

if [[ ${version-NOT-DEFINED} == NOT-DEFINED ]]; then
  version="$(curl -fLsS "$URL_PREFIX"                                     \
               | grep -Eo 'gcc-[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+/' \
               | grep -Eo '[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+'      \
               | LANG=C.UTF-8 sort -Vu                                    \
               | tail -n 1)" \
    || die_with_runtime_error "$PROGRAM_NAME" "Failed to guess GCC latest version."
  if [[ ! $version =~ ^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$ ]]; then
    die_with_runtime_error "$PROGRAM_NAME" "Failed to guess GCC latest version."
  fi
fi
if [[ ! $version =~ ^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$ ]]; then
  die_with_user_error "$PROGRAM_NAME" "An invalid value \`$version' for \`--version' option."
fi

: ${prefix=/usr/local}
configure_options+=("--prefix=$prefix")

temp_dir="$(mktemp -d)" \
  || die_with_runtime_error "$PROGRAM_NAME" "Failed to create a temporary directory."
push_rollback_command "rm -rf \"$temp_dir\""

: ${source_dir="$prefix/src/gcc"}
if [[ -z $source_dir ]]; then
  die_with_user_error "$PROGRAM_NAME" "An invalid value \`$source_dir' for \`--source-dir' option."
fi
if [[ $(readlink -m "$source_dir") != $(cd "$temp_dir" >/dev/null && readlink -m "$source_dir") ]]; then
  die_with_user_error "$PROGRAM_NAME" "A relative path \`$source_dir' is specified for \`--source-dir' option, but is expected to be an absolute one."
fi

if [[ -e $source_dir ]]; then
  case "${clobber_source_dir-no}" in
  yes)
    rm -rf "$source_dir"
    ;;
  no)
    die_with_user_error "$PROGRAM_NAME" "Could not overwrite \`$source_dir'. Use \`--clobber-source-dir' to overwrite it."
    ;;
  *)
    die_with_logic_error "$PROGRAM_NAME"
    ;;
  esac
fi
mkdir -p "$source_dir" \
  || die_with_runtime_error "$PROGRAM_NAME" "Failed to create the source directory \`$source_dir'."

# B215C1633BCA0477615F1B35A5B3A004745C015A: dsa1024          1999-11-09 Gerald Pfeifer <gerald@pfeifer.com>
# B3C42148A44E6983B3E4CC0793FA9B1AB75C61B8: dsa1024          2003-04-10 Mark Mitchell <mark@codesourcery.com>
# 90AA470469D3965A87A5DCB494D03953902C9419: dsa1024          2004-12-06 Gabriel Dos Reis <gdr@acm.org>
# 80F98B2E0DAB6C8281BDF541A7C8C3B2F71EDF1C: dsa1024          2000-02-13 Joseph Samuel Myers <jsm@polyomino.org.uk>
# 7F74F97C103468EE5D750B583AB00996FC26A641: dsa1024          2001-06-26 Richard Guenther <richard.guenther@gmail.com>
# 33C235A34C46AA3FFB293709A328C3A2C3C45C06: dsa1024          2004-04-21 Jakub Jelinek <jakub@redhat.com>
# D3A93CAD751C2AF4F8C7AD516C35B99309B5FA62: RSA4096/09B5FA62 2020-05-28 Jakub Jelinek <jakub@redhat.com>
key_ids=(B215C1633BCA0477615F1B35A5B3A004745C015A  \
         B3C42148A44E6983B3E4CC0793FA9B1AB75C61B8  \
         90AA470469D3965A87A5DCB494D03953902C9419  \
         80F98B2E0DAB6C8281BDF541A7C8C3B2F71EDF1C  \
         7F74F97C103468EE5D750B583AB00996FC26A641  \
         33C235A34C46AA3FFB293709A328C3A2C3C45C06  \
         D3A93CAD751C2AF4F8C7AD516C35B99309B5FA62)
key_servers=('hkp://keys.gnupg.net:80'               \
             'hkp://zimmermann.mayfirst.org:80'      \
             'hkp://pgp.key-server.io:80'            \
             'hkp://keyserver.ubuntu.com:80'         \
             'hkp://p80.pool.sks-keyservers.net:80')
for key_server in "${key_servers[@]}"; do
  gpg --homedir "$temp_dir/.gnupg" --batch --keyserver "$key_server" --recv-keys "${key_ids[@]}" || true
done

(cd "$temp_dir" && curl -fLsSo "gcc-$version.tar.xz" "${URL_PREFIX}gcc-$version/gcc-$version.tar.xz") \
  || die_with_runtime_error "$PROGRAM_NAME" "Failed to download \`gcc-$version.tar.xz'."
(cd "$temp_dir" && curl -fLsSo "gcc-$version.tar.xz.sig" "${URL_PREFIX}gcc-$version/gcc-$version.tar.xz.sig") \
  || die_with_runtime_error "$PROGRAM_NAME" "Failed to download \`gcc-$version.tar.xz.sig'."
gpg --homedir "$temp_dir/.gnupg" --batch --verify "$temp_dir/gcc-$version.tar.xz.sig" "$temp_dir/gcc-$version.tar.xz" \
  || die_with_runtime_error "$PROGRAM_NAME" "Failed to verify the signature in \`gcc-$version.tar.xz.sig'."
rm "$temp_dir/gcc-$version.tar.xz.sig"

tar -xf "$temp_dir/gcc-$version.tar.xz" -C "$source_dir" --strip-components=1 \
  || die_with_runtime_error "$PROGRAM_NAME" "Failed to expand \`gcc-$version.tar.xz'."
rm "$temp_dir/gcc-$version.tar.xz"

(cd "$source_dir" && timeout 60 ./contrib/download_prerequisites) \
  || die_with_runtime_error "$PROGRAM_NAME" "Failed to download the prerequisites to build GCC."
rm "$source_dir"/*.tar.*

build_dir="$temp_dir/build"
mkdir "$build_dir"

(cd "$build_dir" || exit $?
 "$source_dir/configure"                             \
   --disable-multilib                                \
   --enable-languages=c,c++                          \
   ${configure_options[@]+"${configure_options[@]}"}) \
  || die_with_runtime_error "$PROGRAM_NAME" "Failed to \`configure' GCC."

make_options=()

# Check whether this script is (directly or indirectly) called from `make'.
if ! declare -p MAKEFLAGS 2>/dev/null | grep -Eq '^declare -x MAKEFLAGS='; then
  make_options+=(-j -l "$(nproc)")
fi

(cd "$build_dir" && make ${make_options[@]+"${make_options[@]}"}) \
  || die_with_runtime_error "$PROGRAM_NAME" "Failed to \`make' GCC."

(cd "$build_dir" && make install-strip) \
  || die_with_runtime_error "$PROGRAM_NAME" "Failed to \`make install-strip' GCC."
