NUM_TYPES_OF_SPARSE_FEATURES = 510
MAX_NUM_ACTIVE_SPARSE_FEATURES = 29

SEAT_INDEX = 2
SEAT_OFFSET = 7

NUM_NUMERIC_FEATURES = 6

NUM_TYPES_OF_PROGRESSION_FEATURES = 2165
# The following number is actually 106. However, it is set to 109 for
# suitable alignment.
MAX_LENGTH_OF_PROGRESSION_FEATURES = 109

NUM_TYPES_OF_ACTIONS = 546
# The following number is actually 30. However, it is set to 32 for
# suitable alignment.
MAX_NUM_ACTION_CANDIDATES = 32

ENCODER_WIDTH = MAX_NUM_ACTIVE_SPARSE_FEATURES + NUM_NUMERIC_FEATURES \
              + MAX_LENGTH_OF_PROGRESSION_FEATURES + MAX_NUM_ACTION_CANDIDATES

NUM_TYPES_OF_ROUND_SUMMARY = 29
MAX_NUM_ROUND_SUMMARY = 7

NUM_RESULTS = 12


ROUND_NUM_TYPES_OF_SPARSE_FEATURES = 78
ROUND_NUM_SPARSE_FEATURES = 8

ROUND_NUM_NUMERIC_FEATURES = 6

ROUND_NUM_RESULTS = 8

ROUND_ENCODER_WIDTH = ROUND_NUM_SPARSE_FEATURES + ROUND_NUM_NUMERIC_FEATURES


RL_NUM_RESULTS = 8
